packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@nestjs/core": true
  "@prisma/engines": true
  "@swc/core": true
  core-js-pure: false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@yuva-devlab/ui@1.0.0"
  - "@yuva-devlab/tokens@1.0.0"
