import type { Meta, StoryObj } from "@storybook/react";
import { fn } from "@storybook/test";
import { AIInsightCard } from "./AIInsightCard";

/**
 * `AIInsightCard` displays proactive financial recommendations and anomaly notifications
 * generated by the AI Advisor engine. Supports dark and light surface treatments.
 */
const meta: Meta<typeof AIInsightCard> = {
  title: "Components / AIInsightCard",
  component: AIInsightCard,
  tags: ["autodocs"],
  args: {
    title: "OPPORTUNITY",
    body: "You spent 24% less on dining out this month compared to your 3-month average. Reallocating ₹4,200 to your Emergency Fund would hit your target 2 weeks early.",
    cta: "Apply Recommendation",
    variant: "dark",
    onCtaClick: fn(),
  },
  argTypes: {
    variant: {
      control: "radio",
      options: ["dark", "light"],
    },
    cta: { control: "text" },
    title: { control: "text" },
  },
};

export default meta;
type Story = StoryObj<typeof AIInsightCard>;

/** Dark glassmorphism card (default dashboard treatment). */
export const DarkVariant: Story = {};

/** Light surface treatment for high-contrast or light theme layouts. */
export const LightVariant: Story = {
  args: {
    variant: "light",
    title: "TAX SAVINGS",
    body: "Section 80C deduction limit of ₹1,50,000 has ₹32,000 remaining before March 31. Consider an ELSS investment to maximize tax savings.",
    cta: "Explore ELSS Funds",
  },
};

/** Without action button (informational only). */
export const NoCTA: Story = {
  args: {
    cta: undefined,
    title: "ALERT",
    body: "Recurring subscription detected: Streaming Service billed ₹799 on the 1st of every month.",
  },
};
