/**
 * Semantic concept clusters for dynamic category matching.
 *
 * Rather than hardcoding fixed category names (which breaks when users create
 * custom categories like "Self Care", "Salon & Spa", "Daily Commute", etc.),
 * these clusters group related financial concept keywords.
 *
 * If ANY word in a user's category name belongs to the same cluster as ANY
 * word in the user's query, they are dynamically matched.
 */
export const SEMANTIC_CLUSTERS: readonly (readonly string[])[] = [
  // Grooming, Salon & Personal Care
  [
    "haircut",
    "hair cut",
    "salon",
    "barber",
    "grooming",
    "beauty",
    "spa",
    "parlour",
    "parlor",
    "facial",
    "shave",
    "makeup",
    "skincare",
    "self care",
    "hair",
    "massage",
    "waxing",
    "care",
    "personal",
  ],
  // Healthcare, Clinic & Pharmacy
  [
    "doctor",
    "hospital",
    "clinic",
    "medicine",
    "pharmacy",
    "medicines",
    "consultation",
    "chemist",
    "lab",
    "test",
    "health",
    "healthcare",
    "dental",
    "dentist",
    "medical",
    "pills",
    "prescription",
    "checkup",
    "wellness",
  ],
  // Food, Dining & Restaurants
  [
    "restaurant",
    "dining",
    "cafe",
    "coffee",
    "lunch",
    "dinner",
    "breakfast",
    "hotel",
    "bar",
    "pub",
    "snacks",
    "starbucks",
    "canteen",
    "eats",
    "food",
    "tea",
    "chai",
  ],
  // Food Delivery Apps
  ["swiggy", "zomato", "delivery", "food order", "ubereats", "takeaway", "order"],
  // Groceries & Supermarkets
  [
    "groceries",
    "grocery",
    "supermarket",
    "blinkit",
    "zepto",
    "instamart",
    "vegetables",
    "veggies",
    "fruits",
    "milk",
    "dmart",
    "provisions",
    "ration",
    "mart",
  ],
  // Fuel & Petrol
  ["petrol", "diesel", "fuel", "cng", "gas station"],
  // Travel, Cab & Commute
  [
    "cab",
    "taxi",
    "uber",
    "ola",
    "rapido",
    "auto",
    "rickshaw",
    "metro",
    "bus",
    "train",
    "flight",
    "commute",
    "transport",
    "toll",
    "fastag",
    "travel",
  ],
  // Shopping & Ecommerce
  [
    "shopping",
    "amazon",
    "flipkart",
    "myntra",
    "clothes",
    "clothing",
    "shoes",
    "mall",
    "apparel",
    "wear",
    "electronics",
  ],
  // Entertainment & Movies
  [
    "movie",
    "cinema",
    "theatre",
    "theater",
    "concert",
    "show",
    "tickets",
    "pvr",
    "inox",
    "entertainment",
    "game",
    "gaming",
  ],
  // Subscriptions & Streaming
  [
    "netflix",
    "spotify",
    "prime",
    "hotstar",
    "youtube",
    "ott",
    "subscription",
    "apple music",
    "disney",
    "membership",
  ],
  // Internet & Telecom
  [
    "wifi",
    "internet",
    "broadband",
    "mobile recharge",
    "airtel",
    "jio",
    "vi",
    "phone bill",
    "recharge",
    "cellular",
    "telecom",
  ],
  // Utilities & Bills
  [
    "electricity",
    "current bill",
    "eb bill",
    "power bill",
    "water bill",
    "utility",
    "utilities",
    "lpg",
    "gas cylinder",
    "cylinder",
    "bill",
  ],
  // Housing & Rent
  ["rent", "maintenance", "society", "house rent", "flat rent", "housing"],
  // Credit Cards & Debt
  ["credit card", "cc bill", "card payment", "emi", "loan", "debt", "repayment"],
  // Savings & Investments
  [
    "sip",
    "mutual fund",
    "stocks",
    "investment",
    "investments",
    "investing",
    "zerodha",
    "groww",
    "fd",
    "rd",
    "savings",
  ],
  // Income & Salary
  ["salary", "freelance", "consulting", "stipend", "bonus", "dividend", "income", "wage"],
];
