export const FEATURE_FLAGS = {
  AI_INSIGHT: process.env.NEXT_PUBLIC_FEATURE_AI_INSIGHT === "true",
  NOTIFICATIONS: process.env.NEXT_PUBLIC_FEATURE_NOTIFICATIONS === "true",
  SEARCH: process.env.NEXT_PUBLIC_FEATURE_SEARCH === "true",
};

export const SETTING_FLAGS = {
  PROFILE: process.env.NEXT_PUBLIC_SETTING_PROFILE !== "false",
  NOTIFICATIONS: process.env.NEXT_PUBLIC_SETTING_NOTIFICATIONS !== "false",
  CATEGORIES: process.env.NEXT_PUBLIC_SETTING_CATEGORIES !== "false",
  ACCOUNTS: process.env.NEXT_PUBLIC_SETTING_ACCOUNTS !== "false",
  SECURITY: process.env.NEXT_PUBLIC_SETTING_SECURITY !== "false",
  APPEARANCE: process.env.NEXT_PUBLIC_SETTING_APPEARANCE !== "false",
};
